### ISSUE TITLE
Docker Hub: one image or two?

### ISSUE THREAD

**Issue by pacharanero** [inidus/ethercis-docker#9]
@serefarikan @robdyke I'd appreciate views on what you think would be the optimal arrangement for distributing ECIS via Docker Hub. I'm in the process of setting up Automated Builds for the two images used in this repo. ECIS Server and ECIS DB.

-----

Initially I thought having two images (server and db) and then data volumes for PG data and ECIS logs would be a reasonable way to do it, and orchestrate them using docker-compose. This would be an incremental refactor of what you already have here @serefarikan, initially only requiring a change of 

`build: <path/to/Dockerfile>`  to

`image: ethercis-server:latest`

and then Docker will pull from the Hub instead of building locally from the Dockerfile.

-----

However, I notice that actually **both** ECIS-server and ECIS-db require a full JRE (one for ECIS itself and the other for Gradle) - so I actually came to thinking maybe we aren't really gaining anything by separating into two Docker images in this way - apart from making it slightly more complex for ourselves to maintain.

Is there an argument for slapping both postgres and EtherCIS in one image? I still think using separate Docker volumes for persistence outside the container is a good idea for DB data and ECIS logs. But if we could get the whole of EtherCIS in the one Docker box that would probably be advantageous.

Thoughts?

**Comment by jakesmolka** [comment]
How exactly do you think two images would be more complex and one would be advantageous? 

As far as my understanding goes Docker containers (and therefore images) should provide one function/application each [1][2]. So I would keep doing what already is best practice.
Keeping images simple leverages container isolation and helps keeping the whole (e.g. CI) pipeline easier to maintain.

And FYI: There's also this EtherCIS Docker project: https://github.com/skoba/docker-ethercis/

[1] https://surfingthe.cloud/idiomatic-containers/
[2] https://www.packtpub.com/virtualization-and-cloud/mastering-docker-second-edition

**Comment by serefarikan** [comment]
@pacharanero I personally have no use for a single docker image for EtherCIS. Having the DB docker image allows me to use it during Ethercis related development. Rob may have improved the work I've done but I had to consider boot order, what happens if db container stops etc to get that two container setup running. 

It would require undoing some of that but doing in a different way to get a single docker image (the server will just die during startup if the DB is not ready yet) . 

Installing Docker compose is just a small next step for someone who has docker, and you just do docker compose up to get this config running. I'd say it sounds like some effort in exchange for benefits I cannot clearly see. My 2 pennies of course.

**Comment by pacharanero** [comment]
@serefarikan @jakesmolka thanks for the feedback.

@jakesmolka I was purely exploring some of the options available. Since EtherCIS, to many people's understanding, is itself viewed as a 'persistence' in itself, I considered whether it would be advantageous to combine the whole shebang into one image. Part of the reasoning behind this is the duplication in having to have a JRE installed in the `postgres` image so that you can use Gradle to set it up. I'm aware that separate images is better practice in most cases, but I'm also experienced and pragmatic enough to know that _sometimes_ things which are not 'textbook best practice' **do** get done in the real world, for perfectly good reasons. This is the case in medicine as well as tech. 

@serefarikan Thanks for explaining some of your workflow and why having separate images is important to you. That's a clear steer to keeping things as they are, which is fine and was my default position. 

I'm already using docker-compose in the Ripple Stack development environment setup, which currently contains QEWD-Ripple. I can now add the two EtherCIS related images and have it all working automatically.

**Comment by pacharanero** [comment]
Update:
* I have set this up as two separate docker containers, as per feedback in this Issue.
* I was working on these on behalf of the Ripple Foundation which is using EtherCIS as part of its Ripple Showcase Stack and in production in the Helm PHR, so I have put the two dockerfiles in their own repos here but feel free to fork/reuse as wished:
 * https://github.com/RippleOSI/ethercis-server-docker
 * https://github.com/RippleOSI/ethercis-database-docker
* They are separated in this way so as to allow **Automated Builds** on Docker Hub which results in a docker image which you can trust has been built to the spec on the dockerfile and is secure. (Compare with a hand-built container image, which could have had literally _anything_ done to it)
* I have acknowledged in both READMEs that the initial work on these came directly from this repo by @serefarikan 
* We have a Docker Compose file [here](https://github.com/RippleOSI/Ripple-Stack-Vagrant-Docker/tree/master/headless-version) for running these images together. It also runs all the rest of the Ripple Stack Development Environment: Pulsetile (1 container), QEWD-Microservices (5 containers), and EtherCIS (2 containers)
* The same repo contains Vagrantfiles for both Desktop and Headless Ripple Stack development environments (still WIP)
* Any comments or feedback on the above is welcome, but for now I reckon we can close this issue
